### PR TITLE
Upgrading project using Xcode 7.1.1.

### PR DESCRIPTION
**Pull request by JanX2**

### CODE REVIEW

**Comment by Kentzo** [comment]
@JanX2 Will this project be still openable on Mac OS X 10.7 after this update?

**Comment by JanX2** [comment]
@Kentzo It should be. I will check.

**Comment by JanX2** [comment]
I just checked and the project opens fine in Xcode 4.6.3 on Mac OS X 10.7.5. You can’t build it though. This requires ARC and the modern Obj-C runtime, which is 64-bit only on Mac.

**Comment by Kentzo** [comment]
@JanX2 Hmm, arch should have been 64 bit from the beginning. Nor sure why you needed to alter it.

With "Deployment SDK: 10.6 / Base SDK: Latest" I would not expect any errors. Can you reproduce the issue with master's version of xcodeproj? Do you think it's something in xcodeproj itself?

**Comment by JanX2** [comment]
Same errors with your master branch.

I changed “Architectures” to “Native Architecture of Machine” so I could get beyond the ARC errors. Effectively this does:

    ARCHS = "$(NATIVE_ARCH_ACTUAL)";

Then I get a lot of error in this style: 

    …ShortcutRecorder/Library/SRCommon.h:23:14: Unknown type name 'NSEventModifierFlags'; did you mean 'EventModifiers'?

**Comment by JanX2** [comment]
@JanX2
Is there anything preventing this from being merged? I would like to base further work off of this. :)

**Comment by Kentzo** [comment]
@JanX2 Nope :)

**Pull request merged**
