### PR TITLE
Restores support for keyUp/kEventHotKeyReleased

### LINKED ISSUE #102: Restore support for `keyUp` in 3.0
Prior to 3.0, a single hot key could be setup that conveniently allowed for both the `keyUp` and `keyDown` events to be handled. (https://github.com/Kentzo/ShortcutRecorder/pull/18)

Unfortunately, this feature got lost in the 3.0 update. The use case presented in the PR above is still perfectly valid.

### PR DESCRIPTION
**Pull request by gcox**
Resolves #102 

`SRShortcutAction` updated to handle the `kEventHotKeyReleased` and adds new convenience initializers.

### CODE REVIEW

**Comment by Kentzo** [comment]
Good catch!

Is it practical to have the same shortcut action handling both up and down? I'd rather have this logic behind `SRShortcutMonitor`, e.g. `-[SRShortcutMonitor addShortcutAction:forKeyEvent:]`.

**Comment by gcox** [comment]
@Kentzo Yes, that should be fine. I'll look at it tomorrow.

**Comment by gcox** [comment]
@Kentzo I looked at adding the `SRShortcutMonitor` method you suggested, but I didn't see a clear way of implementing it given the current design. Now that `SRShortcutAction` has the `forKeyEvent` property, `SRShortcutMonitor` could get a method like you suggested and mutate the action inside of it, but I don't think that's a good idea.

**Comment by Kentzo** [comment]
I did not spend much time on it, but the idea I have in mind is to have 2 queues per shortcut in the Monitor: one for down and one for up. The monitor then can pick a queue based on the received event.

Can you think of any cases that are ambiguous?

**Comment by gcox** [comment]
I misinterpreted something b/c of getting confused by SRShortcutMonitor and SRShortcutAction being declared/implemented in the same files.

Your idea should be fine...you're basically suggesting another HashTable so we have one for Pressed, one for Released, right?

**Comment by Kentzo** [comment]
I think one should be enough: with values being immutable arrays with 2 mutable arrays.

**Comment by gcox** [comment]
@Kentzo Latest refactor is limited to SRShortcutMonitor

**Comment by Kentzo** [comment]
I'm writing extra tests to ensure that observation still works right. May also remove some old methods due to ambiguity. There will be a follow up PR superseding  this one.

**Comment by Kentzo** [comment]
Superseded by #105

**Pull request closed without merging**
