### PR TITLE
Added dark apperance image assets

### PR DESCRIPTION
**Pull request by flit**
Generated dark mode UI element images and added to `Images.xcassets`.

### CODE REVIEW

**Comment by flit** [comment]
Just saw #82… 🙄  You may close if you prefer the look of the assets in that PR.

**Comment by Kentzo** [comment]
@flit Thanks for the PR!

How did you make the dark version of the images? Do you have a sketch file for that?

**Comment by flit** [comment]
Unfortunately, no. My artist/designer friend created the dark version using Photoshop. It was only after he finished that I discovered the Sketch file. 😦

**Comment by Kentzo** [comment]
Ended up using assets from another source.

**Pull request closed without merging**
