### PR TITLE
Mojave support

### PR DESCRIPTION
**Pull request by nrbrook**
- Merged the janX2 el capitan branch
- Some improvement to code structure
- Recommended project changes and fixed warnings
- Added assets for Mojave and support for dark mode

The dark mode assets are a 'first attempt' and are made by attempting to reproduce the button appearance in Photoshop. I think they are a bit light in normal mode, but this will do for now for my needs. I haven't included highlighted images as I don't know when they are used so can't test and I'm not sure what they are based on. I kept the existing snap back and clear icons as they still look ok in dark mode. Light mode assets are simply the same as El Capitan assets and may need modifying (but I'm not sure if the buttons have actually changed since El Capitan).

### CODE REVIEW

**Comment by nrbrook** [comment]
screenshot 2018-09-30 at 22 49 07

**Comment by nrbrook** [comment]
I’m working on redoing the button states in sketch. Bit difficult to know exactly what the existing button images look like - trying to extract the assets but not sure which ones are the right ones.

**Comment by Kentzo** [comment]
For SR3 I would like to support all the possible style variations: 

- Aqua-Blue
- Aqua-Blue-Accessibility
- Aqua-Graphite
- Aqua-Graphite-Accessibility
- DarkAqua-Blue
- DarkAqua-Blue-Accessibility
- DarkAqua-Graphite
- DarkAqua-Graphite-Accessibility
- VibrantLight-Blue
- VibrantLight-Blue-Accessibility
- VibrantLight-Graphite
- VibrantLight-Graphite-Accessibility
- VibrantDark-Blue
- VibrantDark-Blue-Accessibility
- VibrantDark-Graphite
- VibrantDark-Graphite-Accessibility

I do not have time to draw them myself, so my plan was to extract bitmap images from the system (10.14 through 10.10, starting with 10.14).

The control itself has the following bezels:
- Normal: looks like Push Button
- Pressed: looks like pressed Push Button
- Recording: looks like Search Field
- Disabled: looks like disable Push Button

Now the only issue is that Push Button and Search Field have different height and slightly different corner radius.

I can upload the bitmaps tomorrow so you could take a look and decide if you can redraw it in vector.

**Comment by nrbrook** [comment]
I don’t have time to redraw them, but I could integrate the bitmaps.

**Comment by nrbrook** [comment]
@kentzo are you able to upload the bitmaps?

**Comment by Kentzo** [comment]
Here is some work I did based on macOS bitmaps: https://sketch.cloud/s/Zv1PG

**Comment by Kentzo** [comment]
@nrbrook new assets are now part of the develop branch.

**Pull request closed without merging**
