### PR TITLE
Introduce a new class to hold the key shortcuts

### PR DESCRIPTION
**Pull request by zoul**
The main point of these changes is to have a first-class object for keyboard shortcuts. It makes the interfaces more readable (passing one high-level object instead of a keycode/modifier tuple or a loosely typed dictionary) and provides better code encapsulation and locality (code for working with the keycode/modifier combination is now a part of the class, invisible from the outside). I have also refactored some of the related interfaces to use the new class instead of the keycode/modifier combo.

One serious downside is that the custom class can no longer be stored directly to user defaults. To alleviate this, Ilya suggested that we introduce a `dictionaryValue` property for the `SRRecorderControl` class that could be directly bound to user defaults. I have done that and introduced a new `SRRecorderControlDictionaryValueBinding` constant for the binding. The dictionary serialization used for the `dictionaryValue` is fully compatible with the previous way of storing the shortcuts in a dictionary.

The transformers now expect the new `SRKeyCombo` class instance as an input, but for the sake of backward compatibility they will also accept an `NSDictionary` instance. That means the demo (and other code) should work even with older user defaults contents transparently.

### CODE REVIEW

**Comment by zoul** [comment]
If somebody is interested in a shortcut recording control with simpler code base, there’s [MASShortcut](https://github.com/shpakovski/MASShortcut).

**Comment by Kentzo** [comment]
@zoul Very polite.

**Comment by zoul** [comment]
I’m sorry, I don’t follow. Do you find it offensive to link to a different project with simpler codebase? Why? Or do you disagree about the complexity? If so, I apologize and welcome everybody to make their own conclusions. I closed the pull request since it was sitting here for more than a year without merging, the master branch has diverged long before and I am no longer interested in updating the code for merge.

**Comment by Kentzo** [comment]
I reviewed MAS before and try to review it every few months to see if they find and fix issues related to the codebase of my fork of ShortcutRecorder.

I'm aware that API for registering shortcuts is better in MAS and I want to fix this. By using your PR in particular. The thing it's diverged doesn't mean I cannot manually go through the changes and apply them. And I certainly will.

I'm glad that it was easier for you to go with MAS and update it to the level so it become usable for you. But I gently ask you to create an issue for each problem rather than advertising another Open Source product. My fork is not abandoned by any means.

Anyway, thank you for reminding me. Sometimes good old *ping* works :)

*Subjective*
And no, I do not think MAS codebase is better. It provides a few neat methods to register shorctuts, but that's it. Everything else is below my line of how UI controls should work on Mac OS X.

**Comment by zoul** [comment]
Fair enough, I didn’t mean to criticize Shortcut Recorder, sorry. At the moment, MASShortcut doesn’t support accessibility nor does it offer localization, for example – so there are clear downsides to it, too. Apart from that, could you point out a few specific issues with the MASShortcut control? I don’t want to spam this thread, but a critical hint or two from a person who’s spent some time writing shortcut recording controls could certainly improve MASShortcut. Thanks!

**Comment by Kentzo** [comment]
@zoul I will definitely do during next iteration of reviewing MAS :)

**Comment by Kentzo** [comment]
Will be part of Shortcut Recorder 3.

**Pull request closed without merging**
