### PR TITLE
Update or (minor) fixes on translations

### PR DESCRIPTION
**Pull request by kant**

### CODE REVIEW

**Comment by Kentzo** [comment]
Thank you for the review!

The reason "atajo de teclado" was used in the translation is because I was slowly ditching the "key combination" in favor of "shortcut" in languages that do provide appropriate (compound) nouns. I have updated all strings files to use the new reference.

I also added the "Record Shortcut" string that will replace unnecessarily long "Click to record a shortcut" as a label (it will remain as a tooltip).

I also did a number of changes that rendered the PR conflicting, namely changed the encoding of all strings files into UTF-8.

Please rebase and review the changes.

---

A question: I see that you changed the translation of the modifier keys. Is it how they are called in, say, official Apple language documentation?

**Comment by Kentzo** [comment]
I have noticed that Apple [uses](https://support.apple.com/es-es/HT201236) the term "función rápida". Which one do you think is better?

**Comment by kant** [comment]
@Kentzo : Definitively, _this_ is the way to go. So there will be a new PR reflecting this Apple language guidelines

**Comment by Kentzo** [comment]
Superseded by #108

**Pull request closed without merging**
