### PR TITLE
Add core subspec to podspec to allow for installing without PTHotKey

### PR DESCRIPTION
**Pull request by larsblumberg**
Tested with https://github.com/larsblumberg/shortcutrecorder-cocoapods-demo, corresponding Podfile: https://github.com/larsblumberg/shortcutrecorder-cocoapods-demo/blob/master/Podfile

(Replaces pull request https://github.com/Kentzo/ShortcutRecorder/pull/60)

### CODE REVIEW

**Comment by Kentzo** [comment]
@larsblumberg Could you also contribute instructions for CocoaPods in README?

**Comment by larsblumberg** [comment]
I will create a PR for the README soon

**Comment by Kentzo** [comment]
Thanks!

**Comment by larsblumberg** [comment]
Created a PR: #63

**Pull request merged**
