### PR TITLE
Shortcut Recorder 3.2

### PR DESCRIPTION
**Pull request by Kentzo**

### CODE REVIEW

**Comment by Kentzo** [comment]
@lwouis would you do the honors and green-light the build?

**Comment by lwouis** [comment]
Hey @Kentzo! I don't know what kind of QA/testing you usually run before merging a PR.

I shipped AltTab with the head of `issue-114` this week. I think you've added a few commits since then.

I can run AltTab locally pointing at `develop` and test manually maybe. Would that be useful? :)

**Comment by Kentzo** [comment]
Yup, that should be enough

**Comment by lwouis** [comment]
Hey @Kentzo! Sorry for the delay!

I just tested AltTab with ShortcutRecorder `develop` branch (on commit 631b609), and everything is working great!

**Comment by Kentzo** [comment]
Sure, I will keep it open till June 1st. After I delete it will be accessible for some time, thanks GitHub caching.

**Pull request merged**
